<?php

namespace App\Console\Commands;

use App\Models\User;
use App\Services\AttendanceImportService;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;

/**
 * One-time fix-up: the staff's physical ID cards were already printed
 * with QR codes generated by the original Duscaff system. This maps
 * each already-printed code to the matching user here so scanning a
 * printed card resolves to the right person instead of a mismatched,
 * freshly auto-generated token. Safe to re-run.
 */
#[Signature('attendance:register-original-qr-codes')]
#[Description('Assign the already-printed Duscaff QR codes to their matching users')]
class RegisterOriginalAttendanceQrCodes extends Command
{
    /**
     * @var list<array{name: string, status: string, qr_token: string}>
     */
    private const RECORDS = [
        ['name' => 'Elmar B. Noche', 'status' => 'active', 'qr_token' => 'b1e09940-520e-46bb-9135-f97ca1fa8548'],
        ['name' => 'Jonathan F. Quiles', 'status' => 'active', 'qr_token' => 'fe79d6a8-d02e-4935-a60d-fdba6908c78f'],
        ['name' => 'Dexter L. Javelosa', 'status' => 'active', 'qr_token' => '40f3004f-4d7e-45cf-b75f-0d2255d5cde4'],
        ['name' => 'Rosielyn F. Laron', 'status' => 'active', 'qr_token' => 'd8f8dd3d-331b-437f-8f49-768de234fc35'],
        ['name' => 'Maria Lorena Sheen P. Velasco', 'status' => 'active', 'qr_token' => 'fd9ade8c-3d9a-43f8-81db-30b7c58ca04e'],
        ['name' => 'Fiona Ley Maramba', 'status' => 'active', 'qr_token' => '6684541e-270d-48fe-b1e9-494551fa6d14'],
        ['name' => 'Sheenah Anne Ablen', 'status' => 'inactive', 'qr_token' => '59611dab-5a0b-448a-96d9-b4dcffea6c5f'],
        ['name' => 'Haryll L. Caido', 'status' => 'active', 'qr_token' => '11449c88-7c4b-421d-a3dd-58b72d16dd8a'],
    ];

    public function handle(): int
    {
        $users = User::query()->get(['id', 'name']);
        $usersByName = $users->keyBy(fn (User $user): string => AttendanceImportService::normalizeNameForMatch($user->name));

        $updated = 0;
        $missing = [];

        foreach (self::RECORDS as $record) {
            $user = $usersByName->get(AttendanceImportService::normalizeNameForMatch($record['name']));

            if (! $user instanceof User) {
                $missing[] = $record['name'];

                continue;
            }

            $user->forceFill(['qr_token' => $record['qr_token'], 'status' => $record['status']])->save();
            $updated++;
            $this->info("Registered QR code for {$user->name} (user #{$user->id}).");
        }

        $this->info("Updated {$updated} user(s).");

        if ($missing !== []) {
            $this->warn('No matching user found for: '.implode(', ', $missing).'. Create their account first, then re-run this command.');
        }

        return self::SUCCESS;
    }
}
