<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $timestamp = now();
        $references = [
            ['country' => 'Andorra', 'original_country_code' => 'AD', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'United Arab Emirates', 'original_country_code' => 'AE', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Afghanistan', 'original_country_code' => 'AF', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Antigua and Barbuda', 'original_country_code' => 'AG', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Anguilla', 'original_country_code' => 'AI', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Albania', 'original_country_code' => 'AL', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Armenia', 'original_country_code' => 'AM', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Angola', 'original_country_code' => 'AO', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Argentina', 'original_country_code' => 'AR', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'American Samoa', 'original_country_code' => 'AS', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Austria', 'original_country_code' => 'AT', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Australia', 'original_country_code' => 'AU', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Aruba', 'original_country_code' => 'AW', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Åland Islands', 'original_country_code' => 'AX', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Azerbaijan', 'original_country_code' => 'AZ', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Bosnia and Herzegovina', 'original_country_code' => 'BA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Barbados', 'original_country_code' => 'BB', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Bangladesh', 'original_country_code' => 'BD', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Belgium', 'original_country_code' => 'BE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Burkina Faso', 'original_country_code' => 'BF', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Bulgaria', 'original_country_code' => 'BG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Bahrain', 'original_country_code' => 'BH', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Burundi', 'original_country_code' => 'BI', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Benin', 'original_country_code' => 'BJ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Saint Barthélemy', 'original_country_code' => 'BL', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Bermuda', 'original_country_code' => 'BM', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Brunei Darussalam', 'original_country_code' => 'BN', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Bolivia', 'original_country_code' => 'BO', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Bonaire, Sint Eustatius and Saba', 'original_country_code' => 'BQ', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Brazil', 'original_country_code' => 'BR', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Bahamas', 'original_country_code' => 'BS', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Bhutan', 'original_country_code' => 'BT', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Bouvet Island', 'original_country_code' => 'BV', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Botswana', 'original_country_code' => 'BW', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Belarus', 'original_country_code' => 'BY', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Belize', 'original_country_code' => 'BZ', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Canada', 'original_country_code' => 'CA', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Cocos (Keeling) Islands', 'original_country_code' => 'CC', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Congo (Democratic Republic)', 'original_country_code' => 'CD', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Central African Republic', 'original_country_code' => 'CF', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Congo', 'original_country_code' => 'CG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Switzerland', 'original_country_code' => 'CH', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Côte d\'Ivoire', 'original_country_code' => 'CI', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Cook Islands', 'original_country_code' => 'CK', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Chile', 'original_country_code' => 'CL', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Cameroon', 'original_country_code' => 'CM', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'China', 'original_country_code' => 'CN', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Colombia', 'original_country_code' => 'CO', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Costa Rica', 'original_country_code' => 'CR', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Cuba', 'original_country_code' => 'CU', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Cabo Verde', 'original_country_code' => 'CV', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Curaçao', 'original_country_code' => 'CW', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Christmas Island', 'original_country_code' => 'CX', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Cyprus', 'original_country_code' => 'CY', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Czechia', 'original_country_code' => 'CZ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Germany', 'original_country_code' => 'DE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Djibouti', 'original_country_code' => 'DJ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Denmark', 'original_country_code' => 'DK', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Dominica', 'original_country_code' => 'DM', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Dominican Republic', 'original_country_code' => 'DO', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Algeria', 'original_country_code' => 'DZ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Ecuador', 'original_country_code' => 'EC', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Estonia', 'original_country_code' => 'EE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Egypt', 'original_country_code' => 'EG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Western Sahara', 'original_country_code' => 'EH', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Eritrea', 'original_country_code' => 'ER', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Spain', 'original_country_code' => 'ES', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Ethiopia', 'original_country_code' => 'ET', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Finland', 'original_country_code' => 'FI', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Fiji', 'original_country_code' => 'FJ', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Falkland Islands', 'original_country_code' => 'FK', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Micronesia', 'original_country_code' => 'FM', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Faroe Islands', 'original_country_code' => 'FO', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'France', 'original_country_code' => 'FR', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Gabon', 'original_country_code' => 'GA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'United Kingdom', 'original_country_code' => 'GB', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Grenada', 'original_country_code' => 'GD', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Georgia', 'original_country_code' => 'GE', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'French Guiana', 'original_country_code' => 'GF', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Guernsey', 'original_country_code' => 'GG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Ghana', 'original_country_code' => 'GH', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Gibraltar', 'original_country_code' => 'GI', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Gambia', 'original_country_code' => 'GM', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Guinea', 'original_country_code' => 'GN', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Guadeloupe', 'original_country_code' => 'GP', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Equatorial Guinea', 'original_country_code' => 'GQ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Greece', 'original_country_code' => 'GR', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'South Georgia and the South Sandwich Islands', 'original_country_code' => 'GS', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Guatemala', 'original_country_code' => 'GT', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Guam', 'original_country_code' => 'GU', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Guinea-Bissau', 'original_country_code' => 'GW', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Guyana', 'original_country_code' => 'GY', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Hong Kong', 'original_country_code' => 'HK', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Heard Island and McDonald Islands', 'original_country_code' => 'HM', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Honduras', 'original_country_code' => 'HN', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Croatia', 'original_country_code' => 'HR', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Haiti', 'original_country_code' => 'HT', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Hungary', 'original_country_code' => 'HU', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Indonesia', 'original_country_code' => 'ID', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Ireland', 'original_country_code' => 'IE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Israel', 'original_country_code' => 'IL', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Isle of Man', 'original_country_code' => 'IM', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'India', 'original_country_code' => 'IN', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Iraq', 'original_country_code' => 'IQ', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Iran', 'original_country_code' => 'IR', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Iceland', 'original_country_code' => 'IS', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Italy', 'original_country_code' => 'IT', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Jersey', 'original_country_code' => 'JE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Jamaica', 'original_country_code' => 'JM', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Jordan', 'original_country_code' => 'JO', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Japan', 'original_country_code' => 'JP', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Kenya', 'original_country_code' => 'KE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Kyrgyzstan', 'original_country_code' => 'KG', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Cambodia', 'original_country_code' => 'KH', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Kiribati', 'original_country_code' => 'KI', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Comoros', 'original_country_code' => 'KM', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Saint Kitts and Nevis', 'original_country_code' => 'KN', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Korea (North)', 'original_country_code' => 'KP', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Korea (South)', 'original_country_code' => 'KR', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Kuwait', 'original_country_code' => 'KW', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Cayman Islands', 'original_country_code' => 'KY', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Kazakhstan', 'original_country_code' => 'KZ', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Lao People\'s Democratic Republic', 'original_country_code' => 'LA', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Lebanon', 'original_country_code' => 'LB', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Saint Lucia', 'original_country_code' => 'LC', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Liechtenstein', 'original_country_code' => 'LI', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Sri Lanka', 'original_country_code' => 'LK', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Liberia', 'original_country_code' => 'LR', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Lesotho', 'original_country_code' => 'LS', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Lithuania', 'original_country_code' => 'LT', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Luxembourg', 'original_country_code' => 'LU', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Latvia', 'original_country_code' => 'LV', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Libya', 'original_country_code' => 'LY', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Morocco', 'original_country_code' => 'MA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Monaco', 'original_country_code' => 'MC', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Moldova', 'original_country_code' => 'MD', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Montenegro', 'original_country_code' => 'ME', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Saint Martin (French part)', 'original_country_code' => 'MF', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Madagascar', 'original_country_code' => 'MG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Marshall Islands', 'original_country_code' => 'MH', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'North Macedonia', 'original_country_code' => 'MK', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Mali', 'original_country_code' => 'ML', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Myanmar', 'original_country_code' => 'MM', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Mongolia', 'original_country_code' => 'MN', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Macao', 'original_country_code' => 'MO', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Northern Mariana Islands', 'original_country_code' => 'MP', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Martinique', 'original_country_code' => 'MQ', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Mauritania', 'original_country_code' => 'MR', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Montserrat', 'original_country_code' => 'MS', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Malta', 'original_country_code' => 'MT', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Mauritius', 'original_country_code' => 'MU', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Maldives', 'original_country_code' => 'MV', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Malawi', 'original_country_code' => 'MW', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Malaysia', 'original_country_code' => 'MY', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Mozambique', 'original_country_code' => 'MZ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Namibia', 'original_country_code' => 'NA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'New Caledonia', 'original_country_code' => 'NC', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Niger', 'original_country_code' => 'NE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Norfolk Island', 'original_country_code' => 'NF', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Nigeria', 'original_country_code' => 'NG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Nicaragua', 'original_country_code' => 'NI', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Netherlands', 'original_country_code' => 'NL', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Norway', 'original_country_code' => 'NO', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Nepal', 'original_country_code' => 'NP', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Nauru', 'original_country_code' => 'NR', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Niue', 'original_country_code' => 'NU', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'New Zealand', 'original_country_code' => 'NZ', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Oman', 'original_country_code' => 'OM', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Panama', 'original_country_code' => 'PA', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Peru', 'original_country_code' => 'PE', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'French Polynesia', 'original_country_code' => 'PF', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Papua New Guinea', 'original_country_code' => 'PG', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Philippines', 'original_country_code' => 'PH', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Pakistan', 'original_country_code' => 'PK', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Poland', 'original_country_code' => 'PL', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Saint Pierre and Miquelon', 'original_country_code' => 'PM', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Pitcairn', 'original_country_code' => 'PN', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Puerto Rico', 'original_country_code' => 'PR', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Palestine', 'original_country_code' => 'PS', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Portugal', 'original_country_code' => 'PT', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Palau', 'original_country_code' => 'PW', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Paraguay', 'original_country_code' => 'PY', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Qatar', 'original_country_code' => 'QA', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Réunion', 'original_country_code' => 'RE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Romania', 'original_country_code' => 'RO', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Serbia', 'original_country_code' => 'RS', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Russian Federation', 'original_country_code' => 'RU', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Rwanda', 'original_country_code' => 'RW', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Saudi Arabia', 'original_country_code' => 'SA', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Solomon Islands', 'original_country_code' => 'SB', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Seychelles', 'original_country_code' => 'SC', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Sudan', 'original_country_code' => 'SD', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Sweden', 'original_country_code' => 'SE', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Singapore', 'original_country_code' => 'SG', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Saint Helena, Ascension and Tristan da Cunha', 'original_country_code' => 'SH', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Slovenia', 'original_country_code' => 'SI', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Svalbard and Jan Mayen', 'original_country_code' => 'SJ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Slovakia', 'original_country_code' => 'SK', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Sierra Leone', 'original_country_code' => 'SL', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'San Marino', 'original_country_code' => 'SM', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Senegal', 'original_country_code' => 'SN', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Somalia', 'original_country_code' => 'SO', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Suriname', 'original_country_code' => 'SR', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'South Sudan', 'original_country_code' => 'SS', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Sao Tome and Principe', 'original_country_code' => 'ST', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'El Salvador', 'original_country_code' => 'SV', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Sint Maarten (Dutch part)', 'original_country_code' => 'SX', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Syria', 'original_country_code' => 'SY', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Eswatini', 'original_country_code' => 'SZ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Turks and Caicos Islands', 'original_country_code' => 'TC', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Chad', 'original_country_code' => 'TD', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'French Southern Territories', 'original_country_code' => 'TF', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Togo', 'original_country_code' => 'TG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Thailand', 'original_country_code' => 'TH', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Tajikistan', 'original_country_code' => 'TJ', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Tokelau', 'original_country_code' => 'TK', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Timor-Leste', 'original_country_code' => 'TL', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Turkmenistan', 'original_country_code' => 'TM', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Tunisia', 'original_country_code' => 'TN', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Tonga', 'original_country_code' => 'TO', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Turkey', 'original_country_code' => 'TR', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Trinidad and Tobago', 'original_country_code' => 'TT', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Tuvalu', 'original_country_code' => 'TV', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Taiwan', 'original_country_code' => 'TW', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Tanzania', 'original_country_code' => 'TZ', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Ukraine', 'original_country_code' => 'UA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Uganda', 'original_country_code' => 'UG', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'United States of America', 'original_country_code' => 'US', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Uruguay', 'original_country_code' => 'UY', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Uzbekistan', 'original_country_code' => 'UZ', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
            ['country' => 'Holy See', 'original_country_code' => 'VA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Saint Vincent and the Grenadines', 'original_country_code' => 'VC', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Venezuela', 'original_country_code' => 'VE', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Virgin Islands (British)', 'original_country_code' => 'VG', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Virgin Islands (U.S.)', 'original_country_code' => 'VI', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
            ['country' => 'Viet Nam', 'original_country_code' => 'VN', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Vanuatu', 'original_country_code' => 'VU', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Wallis and Futuna', 'original_country_code' => 'WF', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Samoa', 'original_country_code' => 'WS', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
            ['country' => 'Yemen', 'original_country_code' => 'YE', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
            ['country' => 'Mayotte', 'original_country_code' => 'YT', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'South Africa', 'original_country_code' => 'ZA', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Zambia', 'original_country_code' => 'ZM', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
            ['country' => 'Zimbabwe', 'original_country_code' => 'ZW', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        ];

        DB::table('timezone_references')->upsert(
            array_map(
                fn (array $reference): array => [...$reference, 'created_at' => $timestamp, 'updated_at' => $timestamp],
                $references,
            ),
            ['original_country_code'],
            ['country', 'reference_country_code', 'reference_capital', 'updated_at'],
        );
    }

    /**
     * Reference data intentionally remains available after rollback.
     */
    public function down(): void
    {
        //
    }
};
