<?php

namespace App\Support;

/**
 * Country -> sales region mapping from the team's Regions.xlsx reference
 * (Africa, Asia excluding the Middle East, Oceania, Europe, Middle East,
 * US & Canada, The Americas), keyed by ISO 3166-1 alpha-2 code. Mexico is
 * missing from that spreadsheet and was added to The Americas on request.
 */
class CountryRegions
{
    public const UNASSIGNED = 'Unassigned';

    /** @var list<string> */
    public const REGIONS = ['Africa', 'Asia', 'Oceania', 'Europe', 'Middle East', 'US & Canada', 'The Americas'];

    /** @var array<string, array{name: string, region: string}> */
    public const COUNTRIES = [
        'DZ' => ['name' => 'Algeria', 'region' => 'Africa'],
        'AO' => ['name' => 'Angola', 'region' => 'Africa'],
        'BJ' => ['name' => 'Benin', 'region' => 'Africa'],
        'BW' => ['name' => 'Botswana', 'region' => 'Africa'],
        'BF' => ['name' => 'Burkina Faso', 'region' => 'Africa'],
        'BI' => ['name' => 'Burundi', 'region' => 'Africa'],
        'CV' => ['name' => 'Cabo Verde', 'region' => 'Africa'],
        'CM' => ['name' => 'Cameroon', 'region' => 'Africa'],
        'CF' => ['name' => 'Central African Republic', 'region' => 'Africa'],
        'TD' => ['name' => 'Chad', 'region' => 'Africa'],
        'KM' => ['name' => 'Comoros', 'region' => 'Africa'],
        'CG' => ['name' => 'Congo', 'region' => 'Africa'],
        'CD' => ['name' => 'Congo (Democratic Republic)', 'region' => 'Africa'],
        'CI' => ['name' => 'Côte d\'Ivoire', 'region' => 'Africa'],
        'DJ' => ['name' => 'Djibouti', 'region' => 'Africa'],
        'EG' => ['name' => 'Egypt', 'region' => 'Africa'],
        'GQ' => ['name' => 'Equatorial Guinea', 'region' => 'Africa'],
        'ER' => ['name' => 'Eritrea', 'region' => 'Africa'],
        'SZ' => ['name' => 'Eswatini', 'region' => 'Africa'],
        'ET' => ['name' => 'Ethiopia', 'region' => 'Africa'],
        'GA' => ['name' => 'Gabon', 'region' => 'Africa'],
        'GM' => ['name' => 'Gambia', 'region' => 'Africa'],
        'GH' => ['name' => 'Ghana', 'region' => 'Africa'],
        'GN' => ['name' => 'Guinea', 'region' => 'Africa'],
        'GW' => ['name' => 'Guinea-Bissau', 'region' => 'Africa'],
        'KE' => ['name' => 'Kenya', 'region' => 'Africa'],
        'LS' => ['name' => 'Lesotho', 'region' => 'Africa'],
        'LR' => ['name' => 'Liberia', 'region' => 'Africa'],
        'LY' => ['name' => 'Libya', 'region' => 'Africa'],
        'MG' => ['name' => 'Madagascar', 'region' => 'Africa'],
        'MW' => ['name' => 'Malawi', 'region' => 'Africa'],
        'ML' => ['name' => 'Mali', 'region' => 'Africa'],
        'MR' => ['name' => 'Mauritania', 'region' => 'Africa'],
        'MU' => ['name' => 'Mauritius', 'region' => 'Africa'],
        'YT' => ['name' => 'Mayotte', 'region' => 'Africa'],
        'MA' => ['name' => 'Morocco', 'region' => 'Africa'],
        'MZ' => ['name' => 'Mozambique', 'region' => 'Africa'],
        'NA' => ['name' => 'Namibia', 'region' => 'Africa'],
        'NE' => ['name' => 'Niger', 'region' => 'Africa'],
        'NG' => ['name' => 'Nigeria', 'region' => 'Africa'],
        'RE' => ['name' => 'Réunion', 'region' => 'Africa'],
        'RW' => ['name' => 'Rwanda', 'region' => 'Africa'],
        'SH' => ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'region' => 'Africa'],
        'ST' => ['name' => 'Sao Tome and Principe', 'region' => 'Africa'],
        'SN' => ['name' => 'Senegal', 'region' => 'Africa'],
        'SC' => ['name' => 'Seychelles', 'region' => 'Africa'],
        'SL' => ['name' => 'Sierra Leone', 'region' => 'Africa'],
        'SO' => ['name' => 'Somalia', 'region' => 'Africa'],
        'ZA' => ['name' => 'South Africa', 'region' => 'Africa'],
        'SS' => ['name' => 'South Sudan', 'region' => 'Africa'],
        'SD' => ['name' => 'Sudan', 'region' => 'Africa'],
        'TZ' => ['name' => 'Tanzania', 'region' => 'Africa'],
        'TG' => ['name' => 'Togo', 'region' => 'Africa'],
        'TN' => ['name' => 'Tunisia', 'region' => 'Africa'],
        'UG' => ['name' => 'Uganda', 'region' => 'Africa'],
        'EH' => ['name' => 'Western Sahara', 'region' => 'Africa'],
        'ZM' => ['name' => 'Zambia', 'region' => 'Africa'],
        'ZW' => ['name' => 'Zimbabwe', 'region' => 'Africa'],
        'AF' => ['name' => 'Afghanistan', 'region' => 'Asia'],
        'AM' => ['name' => 'Armenia', 'region' => 'Asia'],
        'AZ' => ['name' => 'Azerbaijan', 'region' => 'Asia'],
        'BD' => ['name' => 'Bangladesh', 'region' => 'Asia'],
        'BT' => ['name' => 'Bhutan', 'region' => 'Asia'],
        'BN' => ['name' => 'Brunei Darussalam', 'region' => 'Asia'],
        'KH' => ['name' => 'Cambodia', 'region' => 'Asia'],
        'CN' => ['name' => 'China', 'region' => 'Asia'],
        'GE' => ['name' => 'Georgia', 'region' => 'Asia'],
        'HK' => ['name' => 'Hong Kong', 'region' => 'Asia'],
        'IN' => ['name' => 'India', 'region' => 'Asia'],
        'ID' => ['name' => 'Indonesia', 'region' => 'Asia'],
        'JP' => ['name' => 'Japan', 'region' => 'Asia'],
        'KZ' => ['name' => 'Kazakhstan', 'region' => 'Asia'],
        'KG' => ['name' => 'Kyrgyzstan', 'region' => 'Asia'],
        'LA' => ['name' => 'Lao People\'s Democratic Republic', 'region' => 'Asia'],
        'MO' => ['name' => 'Macao', 'region' => 'Asia'],
        'MY' => ['name' => 'Malaysia', 'region' => 'Asia'],
        'MV' => ['name' => 'Maldives', 'region' => 'Asia'],
        'MN' => ['name' => 'Mongolia', 'region' => 'Asia'],
        'MM' => ['name' => 'Myanmar', 'region' => 'Asia'],
        'NP' => ['name' => 'Nepal', 'region' => 'Asia'],
        'KP' => ['name' => 'North Korea', 'region' => 'Asia'],
        'PK' => ['name' => 'Pakistan', 'region' => 'Asia'],
        'PH' => ['name' => 'Philippines', 'region' => 'Asia'],
        'SG' => ['name' => 'Singapore', 'region' => 'Asia'],
        'KR' => ['name' => 'South Korea', 'region' => 'Asia'],
        'LK' => ['name' => 'Sri Lanka', 'region' => 'Asia'],
        'TW' => ['name' => 'Taiwan', 'region' => 'Asia'],
        'TJ' => ['name' => 'Tajikistan', 'region' => 'Asia'],
        'TH' => ['name' => 'Thailand', 'region' => 'Asia'],
        'TL' => ['name' => 'Timor-Leste', 'region' => 'Asia'],
        'TM' => ['name' => 'Turkmenistan', 'region' => 'Asia'],
        'UZ' => ['name' => 'Uzbekistan', 'region' => 'Asia'],
        'VN' => ['name' => 'Viet Nam', 'region' => 'Asia'],
        'AS' => ['name' => 'American Samoa', 'region' => 'Oceania'],
        'AU' => ['name' => 'Australia', 'region' => 'Oceania'],
        'BV' => ['name' => 'Bouvet Island', 'region' => 'Oceania'],
        'CX' => ['name' => 'Christmas Island', 'region' => 'Oceania'],
        'CC' => ['name' => 'Cocos (Keeling) Islands', 'region' => 'Oceania'],
        'CK' => ['name' => 'Cook Islands', 'region' => 'Oceania'],
        'FJ' => ['name' => 'Fiji', 'region' => 'Oceania'],
        'PF' => ['name' => 'French Polynesia', 'region' => 'Oceania'],
        'GU' => ['name' => 'Guam', 'region' => 'Oceania'],
        'HM' => ['name' => 'Heard Island and McDonald Islands', 'region' => 'Oceania'],
        'KI' => ['name' => 'Kiribati', 'region' => 'Oceania'],
        'MH' => ['name' => 'Marshall Islands', 'region' => 'Oceania'],
        'FM' => ['name' => 'Micronesia', 'region' => 'Oceania'],
        'NR' => ['name' => 'Nauru', 'region' => 'Oceania'],
        'NC' => ['name' => 'New Caledonia', 'region' => 'Oceania'],
        'NZ' => ['name' => 'New Zealand', 'region' => 'Oceania'],
        'NU' => ['name' => 'Niue', 'region' => 'Oceania'],
        'NF' => ['name' => 'Norfolk Island', 'region' => 'Oceania'],
        'MP' => ['name' => 'Northern Mariana Islands', 'region' => 'Oceania'],
        'PW' => ['name' => 'Palau', 'region' => 'Oceania'],
        'PG' => ['name' => 'Papua New Guinea', 'region' => 'Oceania'],
        'PN' => ['name' => 'Pitcairn', 'region' => 'Oceania'],
        'WS' => ['name' => 'Samoa', 'region' => 'Oceania'],
        'SB' => ['name' => 'Solomon Islands', 'region' => 'Oceania'],
        'TK' => ['name' => 'Tokelau', 'region' => 'Oceania'],
        'TO' => ['name' => 'Tonga', 'region' => 'Oceania'],
        'TV' => ['name' => 'Tuvalu', 'region' => 'Oceania'],
        'VU' => ['name' => 'Vanuatu', 'region' => 'Oceania'],
        'WF' => ['name' => 'Wallis and Futuna', 'region' => 'Oceania'],
        'TF' => ['name' => 'French Southern Territories', 'region' => 'Oceania'],
        'AX' => ['name' => 'Åland Islands', 'region' => 'Europe'],
        'AL' => ['name' => 'Albania', 'region' => 'Europe'],
        'AD' => ['name' => 'Andorra', 'region' => 'Europe'],
        'AT' => ['name' => 'Austria', 'region' => 'Europe'],
        'BY' => ['name' => 'Belarus', 'region' => 'Europe'],
        'BE' => ['name' => 'Belgium', 'region' => 'Europe'],
        'BA' => ['name' => 'Bosnia and Herzegovina', 'region' => 'Europe'],
        'BG' => ['name' => 'Bulgaria', 'region' => 'Europe'],
        'HR' => ['name' => 'Croatia', 'region' => 'Europe'],
        'CY' => ['name' => 'Cyprus', 'region' => 'Europe'],
        'CZ' => ['name' => 'Czechia', 'region' => 'Europe'],
        'DK' => ['name' => 'Denmark', 'region' => 'Europe'],
        'EE' => ['name' => 'Estonia', 'region' => 'Europe'],
        'FO' => ['name' => 'Faroe Islands', 'region' => 'Europe'],
        'FI' => ['name' => 'Finland', 'region' => 'Europe'],
        'FR' => ['name' => 'France', 'region' => 'Europe'],
        'DE' => ['name' => 'Germany', 'region' => 'Europe'],
        'GI' => ['name' => 'Gibraltar', 'region' => 'Europe'],
        'GR' => ['name' => 'Greece', 'region' => 'Europe'],
        'GG' => ['name' => 'Guernsey', 'region' => 'Europe'],
        'VA' => ['name' => 'Holy See', 'region' => 'Europe'],
        'HU' => ['name' => 'Hungary', 'region' => 'Europe'],
        'IS' => ['name' => 'Iceland', 'region' => 'Europe'],
        'IE' => ['name' => 'Ireland', 'region' => 'Europe'],
        'IM' => ['name' => 'Isle of Man', 'region' => 'Europe'],
        'IT' => ['name' => 'Italy', 'region' => 'Europe'],
        'JE' => ['name' => 'Jersey', 'region' => 'Europe'],
        'LV' => ['name' => 'Latvia', 'region' => 'Europe'],
        'LI' => ['name' => 'Liechtenstein', 'region' => 'Europe'],
        'LT' => ['name' => 'Lithuania', 'region' => 'Europe'],
        'LU' => ['name' => 'Luxembourg', 'region' => 'Europe'],
        'MT' => ['name' => 'Malta', 'region' => 'Europe'],
        'MD' => ['name' => 'Moldova', 'region' => 'Europe'],
        'MC' => ['name' => 'Monaco', 'region' => 'Europe'],
        'ME' => ['name' => 'Montenegro', 'region' => 'Europe'],
        'NL' => ['name' => 'Netherlands', 'region' => 'Europe'],
        'MK' => ['name' => 'North Macedonia', 'region' => 'Europe'],
        'NO' => ['name' => 'Norway', 'region' => 'Europe'],
        'PL' => ['name' => 'Poland', 'region' => 'Europe'],
        'PT' => ['name' => 'Portugal', 'region' => 'Europe'],
        'RO' => ['name' => 'Romania', 'region' => 'Europe'],
        'RU' => ['name' => 'Russian Federation', 'region' => 'Europe'],
        'SM' => ['name' => 'San Marino', 'region' => 'Europe'],
        'RS' => ['name' => 'Serbia', 'region' => 'Europe'],
        'SK' => ['name' => 'Slovakia', 'region' => 'Europe'],
        'SI' => ['name' => 'Slovenia', 'region' => 'Europe'],
        'ES' => ['name' => 'Spain', 'region' => 'Europe'],
        'SJ' => ['name' => 'Svalbard and Jan Mayen', 'region' => 'Europe'],
        'SE' => ['name' => 'Sweden', 'region' => 'Europe'],
        'CH' => ['name' => 'Switzerland', 'region' => 'Europe'],
        'TR' => ['name' => 'Turkey', 'region' => 'Europe'],
        'UA' => ['name' => 'Ukraine', 'region' => 'Europe'],
        'GB' => ['name' => 'United Kingdom', 'region' => 'Europe'],
        'BH' => ['name' => 'Bahrain', 'region' => 'Middle East'],
        'IR' => ['name' => 'Iran', 'region' => 'Middle East'],
        'IQ' => ['name' => 'Iraq', 'region' => 'Middle East'],
        'IL' => ['name' => 'Israel', 'region' => 'Middle East'],
        'JO' => ['name' => 'Jordan', 'region' => 'Middle East'],
        'KW' => ['name' => 'Kuwait', 'region' => 'Middle East'],
        'LB' => ['name' => 'Lebanon', 'region' => 'Middle East'],
        'OM' => ['name' => 'Oman', 'region' => 'Middle East'],
        'PS' => ['name' => 'Palestine', 'region' => 'Middle East'],
        'QA' => ['name' => 'Qatar', 'region' => 'Middle East'],
        'SA' => ['name' => 'Saudi Arabia', 'region' => 'Middle East'],
        'SY' => ['name' => 'Syrian Arab Republic', 'region' => 'Middle East'],
        'AE' => ['name' => 'United Arab Emirates', 'region' => 'Middle East'],
        'YE' => ['name' => 'Yemen', 'region' => 'Middle East'],
        'US' => ['name' => 'United States of America', 'region' => 'US & Canada'],
        'CA' => ['name' => 'Canada', 'region' => 'US & Canada'],
        'AI' => ['name' => 'Anguilla', 'region' => 'The Americas'],
        'AG' => ['name' => 'Antigua and Barbuda', 'region' => 'The Americas'],
        'AR' => ['name' => 'Argentina', 'region' => 'The Americas'],
        'AW' => ['name' => 'Aruba', 'region' => 'The Americas'],
        'BS' => ['name' => 'Bahamas', 'region' => 'The Americas'],
        'BB' => ['name' => 'Barbados', 'region' => 'The Americas'],
        'BZ' => ['name' => 'Belize', 'region' => 'The Americas'],
        'BM' => ['name' => 'Bermuda', 'region' => 'The Americas'],
        'BO' => ['name' => 'Bolivia', 'region' => 'The Americas'],
        'BQ' => ['name' => 'Bonaire, Sint Eustatius and Saba', 'region' => 'The Americas'],
        'BR' => ['name' => 'Brazil', 'region' => 'The Americas'],
        'KY' => ['name' => 'Cayman Islands', 'region' => 'The Americas'],
        'CL' => ['name' => 'Chile', 'region' => 'The Americas'],
        'CO' => ['name' => 'Colombia', 'region' => 'The Americas'],
        'CR' => ['name' => 'Costa Rica', 'region' => 'The Americas'],
        'CU' => ['name' => 'Cuba', 'region' => 'The Americas'],
        'CW' => ['name' => 'Curaçao', 'region' => 'The Americas'],
        'DM' => ['name' => 'Dominica', 'region' => 'The Americas'],
        'DO' => ['name' => 'Dominican Republic', 'region' => 'The Americas'],
        'EC' => ['name' => 'Ecuador', 'region' => 'The Americas'],
        'SV' => ['name' => 'El Salvador', 'region' => 'The Americas'],
        'FK' => ['name' => 'Falkland Islands', 'region' => 'The Americas'],
        'GF' => ['name' => 'French Guiana', 'region' => 'The Americas'],
        'GD' => ['name' => 'Grenada', 'region' => 'The Americas'],
        'GP' => ['name' => 'Guadeloupe', 'region' => 'The Americas'],
        'GT' => ['name' => 'Guatemala', 'region' => 'The Americas'],
        'GY' => ['name' => 'Guyana', 'region' => 'The Americas'],
        'HT' => ['name' => 'Haiti', 'region' => 'The Americas'],
        'HN' => ['name' => 'Honduras', 'region' => 'The Americas'],
        'JM' => ['name' => 'Jamaica', 'region' => 'The Americas'],
        'MQ' => ['name' => 'Martinique', 'region' => 'The Americas'],
        'MX' => ['name' => 'Mexico', 'region' => 'The Americas'],
        'MS' => ['name' => 'Montserrat', 'region' => 'The Americas'],
        'NI' => ['name' => 'Nicaragua', 'region' => 'The Americas'],
        'PA' => ['name' => 'Panama', 'region' => 'The Americas'],
        'PY' => ['name' => 'Paraguay', 'region' => 'The Americas'],
        'PE' => ['name' => 'Peru', 'region' => 'The Americas'],
        'PR' => ['name' => 'Puerto Rico', 'region' => 'The Americas'],
        'BL' => ['name' => 'Saint Barthélemy', 'region' => 'The Americas'],
        'KN' => ['name' => 'Saint Kitts and Nevis', 'region' => 'The Americas'],
        'LC' => ['name' => 'Saint Lucia', 'region' => 'The Americas'],
        'MF' => ['name' => 'Saint Martin', 'region' => 'The Americas'],
        'PM' => ['name' => 'Saint Pierre and Miquelon', 'region' => 'The Americas'],
        'VC' => ['name' => 'Saint Vincent and the Grenadines', 'region' => 'The Americas'],
        'SX' => ['name' => 'Sint Maarten', 'region' => 'The Americas'],
        'GS' => ['name' => 'South Georgia and the South Sandwich Islands', 'region' => 'The Americas'],
        'SR' => ['name' => 'Suriname', 'region' => 'The Americas'],
        'TT' => ['name' => 'Trinidad and Tobago', 'region' => 'The Americas'],
        'TC' => ['name' => 'Turks and Caicos Islands', 'region' => 'The Americas'],
        'UY' => ['name' => 'Uruguay', 'region' => 'The Americas'],
        'VE' => ['name' => 'Venezuela', 'region' => 'The Americas'],
        'VG' => ['name' => 'Virgin Islands (British)', 'region' => 'The Americas'],
        'VI' => ['name' => 'Virgin Islands (U.S.)', 'region' => 'The Americas'],
    ];

    public static function regionFor(string $countryCode): string
    {
        return self::COUNTRIES[strtoupper($countryCode)]['region'] ?? self::UNASSIGNED;
    }

    /**
     * Resolve a free-text country name (as stored on older leads without a
     * country_code) to its ISO2 code using the reference names.
     */
    public static function codeForName(string $name): ?string
    {
        static $index = null;
        $index ??= array_change_key_case(array_flip(array_map(fn (array $country): string => $country['name'], self::COUNTRIES)));

        return $index[mb_strtolower(trim($name))] ?? null;
    }
}
