<?php

namespace App\Support;

class TimezoneCleaningReferences
{
    /** @var array<string, array{country: string, reference_country_code: string, reference_capital: string}> */
    private const REFERENCES = [
        'AD' => ['country' => 'Andorra', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'AE' => ['country' => 'United Arab Emirates', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'AF' => ['country' => 'Afghanistan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'AG' => ['country' => 'Antigua and Barbuda', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'AI' => ['country' => 'Anguilla', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'AL' => ['country' => 'Albania', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'AM' => ['country' => 'Armenia', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'AO' => ['country' => 'Angola', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'AR' => ['country' => 'Argentina', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'AS' => ['country' => 'American Samoa', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'AT' => ['country' => 'Austria', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'AU' => ['country' => 'Australia', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'AW' => ['country' => 'Aruba', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'AX' => ['country' => 'Ã…land Islands', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'AZ' => ['country' => 'Azerbaijan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'BA' => ['country' => 'Bosnia and Herzegovina', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BB' => ['country' => 'Barbados', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BD' => ['country' => 'Bangladesh', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'BE' => ['country' => 'Belgium', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BF' => ['country' => 'Burkina Faso', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BG' => ['country' => 'Bulgaria', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BH' => ['country' => 'Bahrain', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'BI' => ['country' => 'Burundi', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BJ' => ['country' => 'Benin', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BL' => ['country' => 'Saint BarthÃ©lemy', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BM' => ['country' => 'Bermuda', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BN' => ['country' => 'Brunei Darussalam', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'BO' => ['country' => 'Bolivia', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BQ' => ['country' => 'Bonaire, Sint Eustatius and Saba', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BR' => ['country' => 'Brazil', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BS' => ['country' => 'Bahamas', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'BT' => ['country' => 'Bhutan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'BV' => ['country' => 'Bouvet Island', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'BW' => ['country' => 'Botswana', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BY' => ['country' => 'Belarus', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'BZ' => ['country' => 'Belize', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CA' => ['country' => 'Canada', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CC' => ['country' => 'Cocos (Keeling) Islands', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'CD' => ['country' => 'Congo (Democratic Republic)', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CF' => ['country' => 'Central African Republic', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CG' => ['country' => 'Congo', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CH' => ['country' => 'Switzerland', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CI' => ['country' => 'Côte d\'Ivoire', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CK' => ['country' => 'Cook Islands', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'CL' => ['country' => 'Chile', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CM' => ['country' => 'Cameroon', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CN' => ['country' => 'China', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'CO' => ['country' => 'Colombia', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CR' => ['country' => 'Costa Rica', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CU' => ['country' => 'Cuba', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CV' => ['country' => 'Cabo Verde', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CW' => ['country' => 'CuraÃ§ao', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'CX' => ['country' => 'Christmas Island', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'CY' => ['country' => 'Cyprus', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'CZ' => ['country' => 'Czechia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'DE' => ['country' => 'Germany', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'DJ' => ['country' => 'Djibouti', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'DK' => ['country' => 'Denmark', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'DM' => ['country' => 'Dominica', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'DO' => ['country' => 'Dominican Republic', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'DZ' => ['country' => 'Algeria', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'EC' => ['country' => 'Ecuador', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'EE' => ['country' => 'Estonia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'EG' => ['country' => 'Egypt', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'EH' => ['country' => 'Western Sahara', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ER' => ['country' => 'Eritrea', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ES' => ['country' => 'Spain', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ET' => ['country' => 'Ethiopia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'FI' => ['country' => 'Finland', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'FJ' => ['country' => 'Fiji', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'FK' => ['country' => 'Falkland Islands', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'FM' => ['country' => 'Micronesia', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'FO' => ['country' => 'Faroe Islands', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'FR' => ['country' => 'France', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GA' => ['country' => 'Gabon', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GB' => ['country' => 'United Kingdom', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GD' => ['country' => 'Grenada', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'GE' => ['country' => 'Georgia', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'GF' => ['country' => 'French Guiana', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'GG' => ['country' => 'Guernsey', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GH' => ['country' => 'Ghana', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GI' => ['country' => 'Gibraltar', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GM' => ['country' => 'Gambia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GN' => ['country' => 'Guinea', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GP' => ['country' => 'Guadeloupe', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'GQ' => ['country' => 'Equatorial Guinea', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GR' => ['country' => 'Greece', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GS' => ['country' => 'South Georgia and the South Sandwich Islands', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'GT' => ['country' => 'Guatemala', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'GU' => ['country' => 'Guam', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'GW' => ['country' => 'Guinea-Bissau', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'GY' => ['country' => 'Guyana', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'HK' => ['country' => 'Hong Kong', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'HM' => ['country' => 'Heard Island and McDonald Islands', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'HN' => ['country' => 'Honduras', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'HR' => ['country' => 'Croatia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'HT' => ['country' => 'Haiti', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'HU' => ['country' => 'Hungary', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ID' => ['country' => 'Indonesia', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'IE' => ['country' => 'Ireland', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'IL' => ['country' => 'Israel', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'IM' => ['country' => 'Isle of Man', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'IN' => ['country' => 'India', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'IQ' => ['country' => 'Iraq', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'IR' => ['country' => 'Iran', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'IS' => ['country' => 'Iceland', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'IT' => ['country' => 'Italy', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'JE' => ['country' => 'Jersey', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'JM' => ['country' => 'Jamaica', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'JO' => ['country' => 'Jordan', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'JP' => ['country' => 'Japan', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'KE' => ['country' => 'Kenya', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'KG' => ['country' => 'Kyrgyzstan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'KH' => ['country' => 'Cambodia', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'KI' => ['country' => 'Kiribati', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'KM' => ['country' => 'Comoros', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'KN' => ['country' => 'Saint Kitts and Nevis', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'KP' => ['country' => 'Korea (North)', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'KR' => ['country' => 'Korea (South)', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'KW' => ['country' => 'Kuwait', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'KY' => ['country' => 'Cayman Islands', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'KZ' => ['country' => 'Kazakhstan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'LA' => ['country' => 'Lao People\'s Democratic Republic', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'LB' => ['country' => 'Lebanon', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'LC' => ['country' => 'Saint Lucia', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'LI' => ['country' => 'Liechtenstein', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'LK' => ['country' => 'Sri Lanka', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'LR' => ['country' => 'Liberia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'LS' => ['country' => 'Lesotho', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'LT' => ['country' => 'Lithuania', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'LU' => ['country' => 'Luxembourg', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'LV' => ['country' => 'Latvia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'LY' => ['country' => 'Libya', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MA' => ['country' => 'Morocco', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MC' => ['country' => 'Monaco', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MD' => ['country' => 'Moldova', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ME' => ['country' => 'Montenegro', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MF' => ['country' => 'Saint Martin (French part)', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'MG' => ['country' => 'Madagascar', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MH' => ['country' => 'Marshall Islands', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'MK' => ['country' => 'North Macedonia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ML' => ['country' => 'Mali', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MM' => ['country' => 'Myanmar', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'MN' => ['country' => 'Mongolia', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'MO' => ['country' => 'Macao', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'MP' => ['country' => 'Northern Mariana Islands', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'MQ' => ['country' => 'Martinique', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'MR' => ['country' => 'Mauritania', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MS' => ['country' => 'Montserrat', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'MT' => ['country' => 'Malta', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MU' => ['country' => 'Mauritius', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MV' => ['country' => 'Maldives', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'MW' => ['country' => 'Malawi', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'MY' => ['country' => 'Malaysia', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'MZ' => ['country' => 'Mozambique', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'NA' => ['country' => 'Namibia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'NC' => ['country' => 'New Caledonia', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'NE' => ['country' => 'Niger', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'NF' => ['country' => 'Norfolk Island', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'NG' => ['country' => 'Nigeria', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'NI' => ['country' => 'Nicaragua', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'NL' => ['country' => 'Netherlands', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'NO' => ['country' => 'Norway', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'NP' => ['country' => 'Nepal', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'NR' => ['country' => 'Nauru', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'NU' => ['country' => 'Niue', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'NZ' => ['country' => 'New Zealand', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'OM' => ['country' => 'Oman', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'PA' => ['country' => 'Panama', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'PE' => ['country' => 'Peru', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'PF' => ['country' => 'French Polynesia', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'PG' => ['country' => 'Papua New Guinea', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'PH' => ['country' => 'Philippines', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'PK' => ['country' => 'Pakistan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'PL' => ['country' => 'Poland', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'PM' => ['country' => 'Saint Pierre and Miquelon', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'PN' => ['country' => 'Pitcairn', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'PR' => ['country' => 'Puerto Rico', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'PS' => ['country' => 'Palestine', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'PT' => ['country' => 'Portugal', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'PW' => ['country' => 'Palau', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'PY' => ['country' => 'Paraguay', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'QA' => ['country' => 'Qatar', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'RE' => ['country' => 'RÃ©union', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'RO' => ['country' => 'Romania', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'RS' => ['country' => 'Serbia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'RU' => ['country' => 'Russian Federation', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'RW' => ['country' => 'Rwanda', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SA' => ['country' => 'Saudi Arabia', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'SB' => ['country' => 'Solomon Islands', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'SC' => ['country' => 'Seychelles', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SD' => ['country' => 'Sudan', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SE' => ['country' => 'Sweden', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SG' => ['country' => 'Singapore', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'SH' => ['country' => 'Saint Helena, Ascension and Tristan da Cunha', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SI' => ['country' => 'Slovenia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SJ' => ['country' => 'Svalbard and Jan Mayen', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SK' => ['country' => 'Slovakia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SL' => ['country' => 'Sierra Leone', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SM' => ['country' => 'San Marino', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SN' => ['country' => 'Senegal', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SO' => ['country' => 'Somalia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SR' => ['country' => 'Suriname', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'SS' => ['country' => 'South Sudan', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ST' => ['country' => 'Sao Tome and Principe', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'SV' => ['country' => 'El Salvador', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'SX' => ['country' => 'Sint Maarten (Dutch part)', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'SY' => ['country' => 'Syria', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'SZ' => ['country' => 'Eswatini', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'TC' => ['country' => 'Turks and Caicos Islands', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'TD' => ['country' => 'Chad', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'TF' => ['country' => 'French Southern Territories', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'TG' => ['country' => 'Togo', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'TH' => ['country' => 'Thailand', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'TJ' => ['country' => 'Tajikistan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'TK' => ['country' => 'Tokelau', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'TL' => ['country' => 'Timor-Leste', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'TM' => ['country' => 'Turkmenistan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'TN' => ['country' => 'Tunisia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'TO' => ['country' => 'Tonga', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'TR' => ['country' => 'Turkey', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'TT' => ['country' => 'Trinidad and Tobago', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'TV' => ['country' => 'Tuvalu', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'TW' => ['country' => 'Taiwan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'TZ' => ['country' => 'Tanzania', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'UA' => ['country' => 'Ukraine', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'UG' => ['country' => 'Uganda', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'US' => ['country' => 'United States of America', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'UY' => ['country' => 'Uruguay', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'UZ' => ['country' => 'Uzbekistan', 'reference_country_code' => 'IN', 'reference_capital' => 'New Delhi'],
        'VA' => ['country' => 'Holy See', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'VC' => ['country' => 'Saint Vincent and the Grenadines', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'VE' => ['country' => 'Venezuela', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'VG' => ['country' => 'Virgin Islands (British)', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'VI' => ['country' => 'Virgin Islands (U.S.)', 'reference_country_code' => 'US', 'reference_capital' => 'New York'],
        'VN' => ['country' => 'Viet Nam', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'VU' => ['country' => 'Vanuatu', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'WF' => ['country' => 'Wallis and Futuna', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'WS' => ['country' => 'Samoa', 'reference_country_code' => 'PH', 'reference_capital' => 'Manila'],
        'YE' => ['country' => 'Yemen', 'reference_country_code' => 'AE', 'reference_capital' => 'Dubai'],
        'YT' => ['country' => 'Mayotte', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ZA' => ['country' => 'South Africa', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ZM' => ['country' => 'Zambia', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
        'ZW' => ['country' => 'Zimbabwe', 'reference_country_code' => 'FR', 'reference_capital' => 'Paris'],
    ];

    /** @return array{country: string, reference_country_code: string, reference_capital: string}|null */
    public static function find(string $countryCode): ?array
    {
        return self::REFERENCES[$countryCode] ?? null;
    }
}
